var states = [
    "distrito federal",
    "aguascalientes",
    "baja california sur",
    "chiapas",
    "chihuahua",
    "estado de mexico",
    "durango",
    "guerrero",
    "guanajuato",
    "hidalgo",
    "michoacan",
    "morelos",
    "nayarit",
    "nuevo leon",
    "oaxaca",
    "puebla",
    "queretaro",
    "san luis potosi",
    "sinaloa",
    "tabasco",
    "tamaulipas",
    "tlaxcala",
    "yucatan",
    "jalisco",
    "campeche",
    "colima",
    "quintana roo",
    "veracruz",
    "zacatecas",
    "sonora",
    "coahuila",
    "baja california norte",
    "baja california",
    "california"
];
module.exports = states;
